USE [master]
GO
/****** Object:  Database [agentappdb]    Script Date: 6/26/2021 2:39:37 PM ******/
CREATE DATABASE [agentappdb]
GO
ALTER DATABASE [agentappdb] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [agentappdb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [agentappdb] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [agentappdb] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [agentappdb] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [agentappdb] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [agentappdb] SET ARITHABORT OFF 
GO
ALTER DATABASE [agentappdb] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [agentappdb] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [agentappdb] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [agentappdb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [agentappdb] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [agentappdb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [agentappdb] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [agentappdb] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [agentappdb] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [agentappdb] SET  DISABLE_BROKER 
GO
ALTER DATABASE [agentappdb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [agentappdb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [agentappdb] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [agentappdb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [agentappdb] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [agentappdb] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [agentappdb] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [agentappdb] SET RECOVERY FULL 
GO
ALTER DATABASE [agentappdb] SET  MULTI_USER 
GO
ALTER DATABASE [agentappdb] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [agentappdb] SET DB_CHAINING OFF 
GO
ALTER DATABASE [agentappdb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [agentappdb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [agentappdb] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [agentappdb] SET QUERY_STORE = OFF
GO
USE [agentappdb]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
USE [agentappdb]
GO
/****** Object:  Table [dbo].[RegisteredUser]    Script Date: 6/26/2021 2:39:37 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RegisteredUser](
	[id] [uniqueidentifier] NOT NULL,
	[username] [nvarchar](50) NOT NULL,
	[email] [nvarchar](254) NOT NULL,
	[first_name] [nvarchar](50) NULL,
	[last_name] [nvarchar](50) NULL,
	[date_of_birth] [datetime2](7) NULL,
	[phone_number] [nvarchar](15) NULL,
	[gender] [nvarchar](6) NULL,
	[website_address] [nvarchar](250) NULL,
	[bio] [nvarchar](250) NULL,
	[type] [nvarchar](20) NOT NULL,
	[password] [nvarchar](256) NOT NULL,
	[profilePicturePath] [nvarchar](250) NULL,
 CONSTRAINT [PK_RegisteredUser] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Item]    Script Date: 6/26/2021 2:39:37 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Item](
	[id] [uniqueidentifier] NOT NULL,
	[name] [nvarchar](50) NOT NULL,
	[item_image_path] [nvarchar](200) NOT NULL,	
	[price] [float] NOT NULL,
	[available_count] [int] NOT NULL,
 CONSTRAINT [PK_Item] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [agentappdb] SET  READ_WRITE 
GO
