FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ["NotificationMicroservice.Api/NotificationMicroservice.Api.csproj", "NotificationMicroservice.Api/"]
COPY ["NotificationMicroservice.DataAccess/NotificationMicroservice.DataAccess.csproj", "NotificationMicroservice.DataAccess/"]
COPY ["NotificationMicroservice.Model/NotificationMicroservice.Core.csproj", "NotificationMicroservice.Model/"]
COPY ["Shared.Contracts/Shared.Contracts.csproj", "Shared.Contracts/"]
COPY . ./

RUN dotnet build "/src/NotificationMicroservice.Api/NotificationMicroservice.Api.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "/src/NotificationMicroservice.Api/NotificationMicroservice.Api.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "NotificationMicroservice.Api.dll"]